---@type LazySpec
return {
  -- "yetone/avante.nvim",
  -- opts = {
  --   mode = "legacy",
  --   provider = "copilot",
  --   hints = { enabled = false },
  --   providers = {
  --     claude = {
  --       endpoint = "https://api.anthropic.com",
  --       model = "claude-opus-4-6",
  --       timeout = 30000, -- Timeout in milliseconds
  --       extra_request_body = {
  --         temperature = 0.75,
  --         max_tokens = 20480,
  --       },
  --     },
  --     copilotclaude = {
  --       __inherited_from = "copilot",
  --       api_key_name = "GITHUB_TOKEN",
  --       model = "claude-opus-4.5",
  --       extra_request_body = {
  --         temperature = 0.75,
  --         max_tokens = 8192,
  --       },
  --     },
  --   },
  -- },
}
